### ISSUE TITLE
Feature Request: Use NERD Fonts for optional icons.

### ISSUE THREAD

**Issue by zoomlogo** [bluz71/vim-moonfly-statusline#10]
Some status line plugins use NERD Font patched fonts for showing the filetype. It will be nice if this plugin had the same feature.

**Comment by bluz71** [comment]
Hello @PyGamer0,

I do not use NERD fonts, therefore, I am unwilling to implement such a feature (being honest).

A PR, if forthcoming from the community, would be judged on merit.

For now, closing as _will-not-implement_.

Best regards.
