### ISSUE TITLE
Feature request: add LF/CR/CRLF indicator

### ISSUE THREAD

**Issue by ayamir** [bluz71/vim-moonfly-statusline#12]

**Comment by bluz71** [comment]
I have no desire for a `LF/CR/CRLF` file format indicator, same goes for file encodings. I do not wish to complicate this plugin with these features.

I use `git config --global core.autocrlf input` which will automatically convert stray `CRLF` to `LF`. With that setting I never need concern myself with `CRLF` when working on Unix platforms.

Regards.

**Comment by ayamir** [comment]
> I have no desire for a `LF/CR/CRLF` file format indicator, same goes for file encodings. I do not wish to complicate this plugin with these features.
> 
> I use `git config --global core.autocrlf input` which will automatically convert stray `CRLF` to `LF`. With that setting I never need concern myself with `CRLF` when working on Unix platforms.
> 
> Regards.

OK, thanks.
