### ISSUE TITLE
Statusline is not activated while starting vim with the netrw buffer open

### ISSUE THREAD

**Issue by hovsater** [bluz71/vim-moonfly-statusline#6]
See attached zip file. As I start Vim (using `vim .`) the statusline isn't active. As soon as I enter command line mode (or any other mode) the statusline activates.

[Screen Recording 2020-02-22 at 12.29.18.zip](https://github.com/bluz71/vim-moonfly-statusline/files/4239325/Screen.Recording.2020-02-22.at.12.29.18.zip)

**Comment by bluz71** [comment]
Yes, that is a case that I missed. Now fixed.

Note, I coded _moonfly-statusline_ specifically to **never** render a styled `statusline` for certain special windows, including file explorers (NERDTree, BufExplorer etc). _netrw_ slipped through the cracks. Now it is handled in the same way as those other file explorers have been, aka use the default `statusline`.

That means there will be no mode indicators, as happens with [NERDTree](https://github.com/preservim/nerdtree) and [BufExplorer](https://github.com/jlanzarotta/bufexplorer) in this plugin.

Why?

Rendering mode indicators for file explorers is not useful, and secondly, _netrw_ specifically renders a custom `statusline` with certain indicators (e.g when copying files from a remote host) that are useful to users.

Thanks for letting me know.
